In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
col=["issue","link","label"]

In [4]:
df=pd.read_csv("train_data.csv")


In [5]:
df.drop(["Unnamed: 0","Unnamed: 0.1"],axis=1,inplace=True)
df.drop(["1"],axis=1,inplace=True)

In [6]:
df.columns=col

In [7]:
df.dropna(axis=0,inplace=True)

In [8]:
X = df.iloc[:,0:1] # X is the features in our dataset
y = df.iloc[:,-1]   # y is the Labels in our dataset
X.shape

(33061, 1)

In [17]:
import nltk

from nltk import word_tokenize
nltk.download('stopwords')





[nltk_data] Downloading package stopwords to /home/varun/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
from nltk.corpus import  stopwords

stopWords =set(stopwords.words('english'))

In [19]:
print(stopWords)

{'hadn', 'very', 'they', 'were', 'wasn', 'don', 'for', 'needn', 'yours', 'should', 'yourselves', 'under', "you'll", "you're", 'those', 'an', 'me', 'above', 'hasn', 'until', 'or', "won't", 'it', 'these', 'below', 'now', 'against', 'with', "didn't", 'shan', 'have', 'other', 'so', "wasn't", 'which', "she's", 'why', 'herself', 'are', 'mustn', 'been', 'to', 'further', "hadn't", 'before', 've', 'because', 'there', "you'd", 'hers', 'through', "don't", "wouldn't", 'whom', 'on', 'won', 'just', 'not', 'the', 'is', 'd', 'between', 'doing', 'from', "mustn't", 'out', 'by', 'didn', "weren't", "should've", 'wouldn', 'ain', 'few', 'some', 'she', 'i', 'aren', 'in', "shouldn't", 'we', "needn't", 'did', 'll', 'has', 'who', 'each', 'theirs', 'had', 'here', 'our', 's', 'haven', "haven't", 'of', 'himself', 'he', 'both', 'same', 'ours', 'any', 'after', 'about', 'him', 'more', 'their', 'over', 'again', 'can', 'shouldn', 'its', 'ourselves', 'does', 'while', 'all', 'his', 'having', "isn't", "shan't", 'my', 'thi

In [20]:
import string

In [21]:
def dataclean(a):
    remove_punctuation=[char for char in a if char  not in string.punctuation ]
    remove_punctuation="".join(remove_punctuation)
    return [word  for word in remove_punctuation.split() if word.lower() not in stopwords.words('english')]

In [23]:
data=df[["issue","label"]]

In [24]:
data

issue    label
0      TextVectorization inconsistency depending on o...      bug
1      Cant install tflite_runtime while deploying on...    build
2      [TF2.3.0] Failed to Build libtensorflow_cc.so ...    build
3                  Optimize unique_op by repetition rate  feature
4      pip and conda install tensorflow problems in a...    build
...                                                  ...      ...
33057  Add performance and accuracy regression testin...  feature
33058  expose backend selection and cudnn settings to...  feature
33059        improve parallel performance for RNN models  feature
33060                          Error messages to improve    error
33061     Support multi-type operations where reasonable  feature

[33061 rows x 2 columns]

In [47]:
data.iloc[:,0].apply(dataclean)

0        [TextVectorization, inconsistency, depending, ...
1        [Cant, install, tfliteruntime, deploying, web,...
2        [TF230, Failed, Build, libtensorflowccso, C, A...
3                   [Optimize, uniqueop, repetition, rate]
4        [pip, conda, install, tensorflow, problems, an...
                               ...                        
33057    [Add, performance, accuracy, regression, testi...
33058    [expose, backend, selection, cudnn, settings, ...
33059        [improve, parallel, performance, RNN, models]
33060                           [Error, messages, improve]
33061         [Support, multitype, operations, reasonable]
Name: issue, Length: 33061, dtype: object

In [48]:
data

issue    label
0      TextVectorization inconsistency depending on o...      bug
1      Cant install tflite_runtime while deploying on...    build
2      [TF2.3.0] Failed to Build libtensorflow_cc.so ...    build
3                  Optimize unique_op by repetition rate  feature
4      pip and conda install tensorflow problems in a...    build
...                                                  ...      ...
33057  Add performance and accuracy regression testin...  feature
33058  expose backend selection and cudnn settings to...  feature
33059        improve parallel performance for RNN models  feature
33060                          Error messages to improve    error
33061     Support multi-type operations where reasonable  feature

[33061 rows x 2 columns]

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer =CountVectorizer(analyzer=dataclean).fit(data["issue"])
bow_transformer.vocabulary_

{'TextVectorization': 10494,
 'inconsistency': 18495,
 'depending': 15388,
 'outputsequencelength': 22268,
 'Cant': 2734,
 'install': 18750,
 'tfliteruntime': 27909,
 'deploying': 15394,
 'web': 30009,
 'application': 12060,
 'online': 21905,
 'TF230': 10023,
 'Failed': 4448,
 'Build': 2253,
 'libtensorflowccso': 19759,
 'C': 2282,
 'APIs': 1451,
 'conda': 13857,
 'environment': 16255,
 'Optimize': 7690,
 'uniqueop': 29294,
 'repetition': 23898,
 'rate': 23537,
 'pip': 22635,
 'tensorflow': 26082,
 'problems': 23033,
 'anaconda': 11946,
 'TensorFlowKeras': 10325,
 'Code': 2922,
 'Example': 4258,
 'webgl': 30013,
 'backend': 12449,
 'image': 18283,
 'width': 30087,
 'odd': 21849,
 'second': 24566,
 'run': 24274,
 'tfconv2d': 27216,
 'may': 20415,
 'wrong': 30223,
 'Bug': 2243,
 'Issues': 5812,
 'Testing': 10488,
 'Add': 1594,
 'additivemultiplicative': 11750,
 'angluar': 11998,
 'margin': 20284,
 'loss': 20085,
 'modelfit': 20806,
 'ends': 16207,
 'epochs': 16259,
 'ran': 23489,
 'Proce

In [27]:
title_bow=bow_transformer.transform(data["issue"])

In [28]:
print(title_bow)

  (0, 10494)	1
  (0, 15388)	1
  (0, 18495)	1
  (0, 22268)	1
  (1, 2734)	1
  (1, 12060)	1
  (1, 15394)	1
  (1, 18750)	1
  (1, 21905)	1
  (1, 27909)	1
  (1, 30009)	1
  (2, 1451)	1
  (2, 2253)	1
  (2, 2282)	1
  (2, 4448)	1
  (2, 10023)	1
  (2, 13857)	1
  (2, 16255)	1
  (2, 19759)	1
  (3, 7690)	1
  (3, 23537)	1
  (3, 23898)	1
  (3, 29294)	1
  (4, 11946)	1
  (4, 13857)	1
  :	:
  (33056, 1594)	1
  (33056, 11680)	1
  (33056, 21306)	1
  (33056, 22535)	1
  (33056, 23781)	1
  (33056, 26801)	1
  (33057, 12449)	1
  (33057, 14656)	1
  (33057, 16196)	1
  (33057, 16590)	1
  (33057, 24615)	1
  (33057, 24770)	1
  (33057, 29480)	1
  (33058, 8541)	1
  (33058, 18416)	1
  (33058, 20847)	1
  (33058, 22382)	1
  (33058, 22535)	1
  (33059, 4206)	1
  (33059, 18416)	1
  (33059, 20495)	1
  (33060, 9887)	1
  (33060, 21084)	1
  (33060, 22101)	1
  (33060, 23606)	1


In [29]:
from sklearn.feature_extraction.text import TfidfTransformer


In [30]:
tfidf_transformer=TfidfTransformer().fit(title_bow)
print(tfidf_transformer)

TfidfTransformer()


In [31]:
title_tfidf=tfidf_transformer.transform(title_bow)
print(title_tfidf)
print(title_tfidf.shape)

  (0, 22268)	0.5831574534374955
  (0, 18495)	0.4635524161879692
  (0, 15388)	0.4699638884208726
  (0, 10494)	0.473477016894088
  (1, 30009)	0.4042764328693884
  (1, 27909)	0.40748313607135295
  (1, 21905)	0.41464786871595033
  (1, 18750)	0.26247663100164753
  (1, 15394)	0.4553385711434253
  (1, 12060)	0.3752665137532833
  (1, 2734)	0.2855399307902902
  (2, 19759)	0.41013476296384055
  (2, 16255)	0.3541430418848759
  (2, 13857)	0.3541430418848759
  (2, 10023)	0.48965660934995364
  (2, 4448)	0.2656470535145989
  (2, 2282)	0.2546794027178471
  (2, 2253)	0.25411985845602936
  (2, 1451)	0.3757451732572695
  (3, 29294)	0.5807499097246483
  (3, 23898)	0.543174493184159
  (3, 23537)	0.4107751849790952
  (3, 7690)	0.44604345047801647
  (4, 26082)	0.2359871842500553
  (4, 23033)	0.41479989527856953
  :	:
  (33056, 26801)	0.451766649348422
  (33056, 23781)	0.3855346299892643
  (33056, 22535)	0.35696803408152944
  (33056, 21306)	0.5273405663676951
  (33056, 11680)	0.40903489131906334
  (33056, 159

In [49]:
data

issue    label
0      TextVectorization inconsistency depending on o...      bug
1      Cant install tflite_runtime while deploying on...    build
2      [TF2.3.0] Failed to Build libtensorflow_cc.so ...    build
3                  Optimize unique_op by repetition rate  feature
4      pip and conda install tensorflow problems in a...    build
...                                                  ...      ...
33057  Add performance and accuracy regression testin...  feature
33058  expose backend selection and cudnn settings to...  feature
33059        improve parallel performance for RNN models  feature
33060                          Error messages to improve    error
33061     Support multi-type operations where reasonable  feature

[33061 rows x 2 columns]

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(title_tfidf, data["label"], test_size=0.2, random_state=42)

In [57]:
from sklearn.naive_bayes import MultinomialNB
model =MultinomialNB().fit(X_train,y_train)

In [58]:
predicted=model.predict(X_test)
print(predicted.shape)

(6613,)


In [63]:
print(pd.DataFrame(y_test))

             label
19295          bug
21600          bug
8194           bug
16574          bug
29784  enhancement
...            ...
11571        build
28163          bug
1347       support
16322      feature
20640          bug

[6613 rows x 1 columns]


In [59]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
print("Accuracy:\n",accuracy_score(y_test,predicted))
print()
#print(metrics.classification_report(y_test,predicted,target_names=y_test))
print()
print("confusion matrix:\n",metrics.confusion_matrix(y_test,predicted))


Accuracy:
 0.5378799334643883


confusion matrix:
 [[  21  282   25    0    0    6    0    0    0]
 [   1 2364  160    0    0   12    0    0   20]
 [   0  378  930    0    0    5    0    0    2]
 [   0  188   10    0    0   46    0    0    0]
 [   0   22    0    0    0    0    0    0    0]
 [   0  643   45    0    0  216    0    0    6]
 [   0   41    0    0    0    1    0    0    0]
 [   0  180    8    0    0    3    0    0    0]
 [   0  846  120    0    0    6    0    0   26]]


In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data["issue"], data["label"], test_size=0.33, random_state=42)

In [41]:
X_train

21174      Extend ClassifierChain to multi-output problems
3018                                LSTM Input Shape Error
9374     save_weights does not work for scalars in kera...
29650                                   DCT for odd length
8886                  ImportError: DLL load failed TF 1.13
                               ...                        
16851    Some small problems with the RNN and seq2seq i...
6265                              TF looking for CUDA 10.1
11285                                ReorderAxes in TFLite
860      Issue on using tf.vectorized_map on a function...
15796    Iterator on cached tf.data Dataset cannot be r...
Name: issue, Length: 22150, dtype: object

In [45]:
X_train[0].apply(dataclean)
X_test[0].apply(dataclean)

AttributeError: 'str' object has no attribute 'apply'